### ISSUE TITLE
Unable to install build "beforeBuildCommand `npm run build` failed with exit code 1"

### ISSUE THREAD

**Issue by RayFernando1337** [ceorkm/grably#1]
Steps to reproduce:
1. clone repo
2. `npm install`
3. `./download-binaries.sh`
4. `npm run tauri build`

❯ npm run tauri build

> grably-desktop@0.1.0 tauri
> tauri build

        Info Looking up installed tauri packages to check mismatched versions...
     Running beforeBuildCommand `npm run build`

> grably-desktop@0.1.0 build
> tsc && vite build

vite v5.4.19 building for production...
✓ 0 modules transformed.
x Build failed in 7ms
error during build:
Could not resolve entry module "landing.html".
    at getRollupError (file:///Users/ray/workspace/grably/node_modules/rollup/dist/es/shared/parseAst.js:401:41)
    at error (file:///Users/ray/workspace/grably/node_modules/rollup/dist/es/shared/parseAst.js:397:42)
    at ModuleLoader.loadEntryModule (file:///Users/ray/workspace/grably/node_modules/rollup/dist/es/shared/node-entry.js:21555:20)
    at async Promise.all (index 1)
beforeBuildCommand `npm run build` failed with exit code 1
       Error beforeBuildCommand `npm run build` failed with exit code 1

**Comment by ceorkm** [comment]
Hi @RayFernando1337!

  Thanks for reporting this issue. I've just pushed a fix for the TypeScript build
  error. The problem was an unused import in the LandingPage component that was causing
  the build to fail.

  Please try again:
  1. `git pull` (to get the latest changes)
  2. `npm run tauri build`

**Comment by RayFernando1337** [comment]
I ran the latest changes and I'm still seeing the same issue. Cleared out the repo, retried and same thing.

❯ npm run tauri build

   > grably-desktop@0.1.0 tauri
   > tauri build

           Info Looking up installed tauri packages to check mismatched 
   versions...
        Running beforeBuildCommand `npm run build`

   > grably-desktop@0.1.0 build
   > tsc && vite build

   vite v5.4.19 building for production...
   ✓ 0 modules transformed.
   x Build failed in 9ms
   error during build:
   Could not resolve entry module "landing.html".
       at getRollupError (file:///Users/ray/workspace/grably/node_modules/rollu
   p/dist/es/shared/parseAst.js:401:41)
       at error (file:///Users/ray/workspace/grably/node_modules/rollup/dist/es
   /shared/parseAst.js:397:42)
       at ModuleLoader.loadEntryModule (file:///Users/ray/workspace/grably/node
   _modules/rollup/dist/es/shared/node-entry.js:21555:20)
       at async Promise.all (index 1)
   beforeBuildCommand `npm run build` failed with exit code 1
          Error beforeBuildCommand `npm run build` failed with exit code 1

**Comment by RayFernando1337** [comment]
I ran a Factory AI droid on it and here is what it is telling me is the RCA:

Findings                                                              │
│ •  Root cause: vite.config.ts still declares a multi‑page input with  │
│    landing: resolve(__dirname, 'landing.html'), but the repo does not │
│    contain landing.html (it’s ignored by the root .gitignore via      │
│    /landing.html and was removed in commit 6479f97). Vite/rollup fails│
│     before Tauri bundling. This is unrelated to src-tauri/.gitignore. │
│                                                                       │
│ •  Commit b60fc3a (“Fix build failure by removing unused Github       │
│    import”) didn’t touch vite.config.ts, so the failure persists.

**Comment by RayFernando1337** [comment]
```
diff --git a/vite.config.ts b/vite.config.ts
index 8bf986a..7d81ffd 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -2,8 +2,13 @@ import { defineConfig } from 'vite'
 import react from '@vitejs/plugin-react'
 import path from 'path'
 import { resolve } from 'path'
+import { existsSync } from 'node:fs'
 
 // https://vitejs.dev/config/
+const inputs: Record<string, string> = { main: resolve(__dirname, 'index.html') }
+const landingPath = resolve(__dirname, 'landing.html')
+if (existsSync(landingPath)) inputs.landing = landingPath
+
 export default defineConfig({
   plugins: [react()],
   resolve: {
@@ -20,10 +25,7 @@ export default defineConfig({
     minify: !process.env.TAURI_DEBUG ? 'esbuild' : false,
     sourcemap: !!process.env.TAURI_DEBUG,
     rollupOptions: {
-      input: {
-        main: resolve(__dirname, 'index.html'),
-        landing: resolve(__dirname, 'landing.html'),
-      },
+      input: inputs,
     },
   },
 })
\ No newline at end of file

```
